options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - PROJECT_ID=$PROJECT_ID
    - REGION=$_REGION
    - SERVICE_ACCOUNT=$_SERVICE_ACCOUNT
    - TRAIN_IMAGE_URI=$_TRAIN_IMAGE_URI
    - PIPELINE_STAGING=$_PIPELINE_STAGING
    - PIPELINE_ROOT=$_PIPELINE_ROOT
    - TENSORBOARD_ID=$_TENSORBOARD_ID
    - KFP_REPO=$_KFP_REPO
    - HF_DATASET_REPO=$_HF_DATASET_REPO
    - HF_SECRET_ID=$_HF_SECRET_ID
    - GITHUB_REPO=$_GITHUB_REPO
    - GITHUB_SECRET_ID=$_GITHUB_SECRET_ID

serviceAccount: projects/$PROJECT_ID/serviceAccounts/$_SERVICE_ACCOUNT

steps:
  - id: "Update ainu-mt5-pipeline"
    name: python:3.11
    entrypoint: bash
    args:
      - "-c"
      - |
        pip install -q "." \
        && ainu-lm-pipeline compile mt \
        && ainu-lm-pipeline push mt \
    # && ainu-lm-pipeline schedule mt --cron "TZ=Asia/Tokyo 0 0 * * MON"
    # waitFor: ["-"]
